### ISSUE TITLE
error: device_control_input: Got unhandled payload type 5

### ISSUE THREAD

**Issue by dhreben** [zebrunner/mcloud-ios-connector#13] opened 2024-06-03 07:50 UTC
error is reproduced after 24+ hours of inactivity on some ios devices

**connector log:** 
```

[17:48:46.006][1] ERROR: client_write: sending to fd 13 failed: Broken pipe
[17:48:46.006][1] ERROR: client_write: sending to fd 13 failed: Broken pipe
[17:48:46.006][1] connection_teardown: aborting buffer flush to client after error.
[17:48:46.012][2] device_control_input: Got unhandled payload type 5
[17:48:47.281][2] device_control_input: Got unhandled payload type 5
```

**container logs:** 

```
2024-06-02T21:16:09.801Z IMP/device:plugins:group 55 [0000........................001E] No longer owned by "qps-auto@qaprosoft.com"
2024-06-02T21:16:09.801Z INF/device:plugins:group 55 [000.......................001E] Unsubscribing from group channel "vIReE84DT3m47YNuLoA26Q=="
2024-06-02T21:16:09.837Z IMP/device:plugins:group 55 [000...................8001E] Now owned by "qps-auto@qaprosoft.com"
2024-06-02T21:16:09.837Z INF/device:plugins:group 55 [00008................8001E] Subscribing to group channel "vIReE84DT3m47YNuLoA26Q=="
2024-06-02T21:28:43.225Z INF/util:lifecycle 55 [00.................001E] Winding down for graceful exit, with optional error :  WdaMjpeg connection is lost
2024-06-02T21:28:43.226Z FTL/util:lifecycle 55 [000.............001E] Shutting down due to fatal error with optional error :  WdaMjpeg connection is lost
WdaMjpeg connection was closed
Exit status: 1
```

**Appium log:** 

```
appium --log-no-colors --log-timestamp -pa /wd/hub --port 7711 --log /tmp/log/appium.log --log-level info --session-override --nodeconfig /root/nodeconfig.json --default-capabilities /root/defaultcapabilities.json --relaxed-security --allow-insecure chromedriver_autodownload
Couldn't initialize inotify.  Are you running Linux 2.6.13 or later, and was the
CONFIG_INOTIFY option enabled when your kernel was compiled?  If so, 
something mysterious has gone wrong.  Please e-mail rad.............mail.com
 and mention that you saw this message.
Exit status: 0
exit_code: 0
```

**Comment by vdelendik** [comment] 2024-06-03 17:30
closed as dupe of https://github.com/zebrunner/mcloud-agent/issues/328
added extra documentation step howto workaround for mcloud-agent repo

**Closed by vdelendik** 2024-06-03 17:30 UTC
Labels: bug, duplicate
